### ISSUE TITLE
Minor Todo Items for Sprint 3

### ISSUE THREAD

**Issue by CharlesBarone** [UNH-iOS-Spring2023/Security-Intelligence-Toolkit-iOS-Barone-Mahr#34]
- [x] IPv4 validation for shodan ip search
- [x] make sure query string is not empty before allowing run shodan button to be pressed
- [x] alerts for shodan query status/errors
- [x] remove debug print messages from shodan
- [x] Make it so history results are in order
